import Head from 'next/head'
import Content from '../../components/Content'
import Header from '../../components/Header'
// import Nav from '../../components/Nav'
// import requests from '../../utils/requests'

// import axios from "axios";
import { server } from '../../config';

import {useRouter} from "next/router";
import { Store } from "../../utils/Store";
import { useContext, useEffect } from 'react'
import Link from 'next/link';
import Cookies from 'js-cookie';

export const getServerSideProps = async (context)=>{
  const email = (Cookies.get('userInfo')?JSON.parse(Cookies.get('userInfo')):null)
  // console.log(context);
    const request = await fetch(`${server}/api/getFav`,{method: "POST",body: JSON.stringify(email)})
    const {data} = await request.json();
  
    return {
      props:{
        data
      }
    }
}

export default function Home({data}) {
    // console.log(!!data[0],data[0]);
    const router = useRouter();
    const {state,dispatch} = useContext(Store)
    const {userInfo} = state;
    useEffect(() => {
      if(!userInfo){
        router.push( "/login")
      }
  }, []);
  return (
    <div>
      <Head>
        <title>Popular Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header/>

      {/* content */}

      {data[0]?(<Content data={data}/>):(<div>
        <h2>
          Favourite List is Empty. Please go to <Link  href="/discover">
            <a className="text-yellow-500">
              Home page
            </a>
          </Link>
        </h2>
      </div>)}
      
    </div>
  )
}


